# Generated by Django 4.0.5 on 2022-07-06 13:57

import account.validation
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('memberID', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('memberName', models.CharField(default='', max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=11, unique=True, validators=[account.validation.validate_password])),
                ('gender', models.SmallIntegerField(choices=[(0, 'Female'), (1, 'Male')])),
                ('email', models.EmailField(max_length=128, validators=[account.validation.validate_password])),
                ('address', models.CharField(max_length=200)),
                ('point', models.IntegerField(blank=True)),
                ('membership', models.SmallIntegerField(choices=[(1, '아기집사'), (2, '어린이집사'), (3, '청년집사'), (4, '베테랑집사')], default=1)),
                ('followings', models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Suspend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cause', models.CharField(max_length=300)),
                ('suspendedUser', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspendedUsers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('intorduction', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/photo')),
                ('memberId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('accusedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accusedUsers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
