# Generated by Django 4.0.5 on 2022-07-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='memberID',
        ),
        migrations.AddField(
            model_name='member',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='memberId',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
