# Generated by Django 4.0.6 on 2022-07-06 17:02

import account.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=128, null=True, validators=[account.validation.validate_password]),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'Female'), (1, 'Male')], null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberName',
            field=models.CharField(default='', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership',
            field=models.SmallIntegerField(choices=[(1, '아기집사'), (2, '어린이집사'), (3, '청년집사'), (4, '베테랑집사')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phoneNumber',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[account.validation.validate_email]),
        ),
        migrations.AlterField(
            model_name='member',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
