# Generated by Django 4.0.5 on 2022-07-06 17:01

import account.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_member_memberid_member_id_member_memberid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phoneNumber',
            field=models.CharField(max_length=11, unique=True, validators=[account.validation.validate_email]),
        ),
    ]
