# Generated by Django 4.0.5 on 2022-07-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_member_followings_member_membership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership',
            field=models.SmallIntegerField(choices=[(1, '아기집사'), (2, '어린이집사'), (3, '청년집사'), (4, '베테랑집사')], default=1),
        ),
    ]
