# Generated by Django 4.0.5 on 2022-07-06 17:48

import account.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_member_address_alter_member_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=128, null=True, validators=[account.validation.validate_email]),
        ),
        migrations.AlterField(
            model_name='member',
            name='phoneNumber',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[account.validation.validate_password]),
        ),
    ]
