# Generated by Django 4.0.5 on 2022-07-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_member_email_alter_member_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberName',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
