# Generated by Django 4.0.6 on 2022-07-06 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_member_address_alter_member_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='memberId',
        ),
    ]
