# Generated by Django 4.0.6 on 2022-07-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_postimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='hashtag',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
