# Generated by Django 4.0.5 on 2022-07-06 12:58

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_post_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=board.models.get_image_filename),
        ),
    ]
